// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// Account is the golang structure for table account.
type Account internal.Account

// Fill with you ideas below.