// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// AppDefList is the golang structure for table app_def_list.
type AppDefList internal.AppDefList

// Fill with you ideas below.