// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// Check is the golang structure for table check.
type Check internal.Check

// Fill with you ideas below.