// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// Eba is the golang structure for table eba.
type Eba internal.Eba

// Fill with you ideas below.