// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// Edt is the golang structure for table edt.
type Edt internal.Edt

// Fill with you ideas below.