// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// EdtIo is the golang structure for table edt_io.
type EdtIo internal.EdtIo

// Fill with you ideas below.