// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// Emp is the golang structure for table emp.
type Emp internal.Emp

// Fill with you ideas below.