// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// InitEba is the golang structure for table init_eba.
type InitEba internal.InitEba

// Fill with you ideas below.