// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// InitInvRes is the golang structure for table init_inv_res.
type InitInvRes internal.InitInvRes

// Fill with you ideas below.