// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// InvRes is the golang structure for table inv_res.
type InvRes internal.InvRes

// Fill with you ideas below.