// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// InvEba is the golang structure for table inv_eba.
type InvEba internal.InvEba

// Fill with you ideas below.