// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fmt"
	"gfast/app/model/internal"
)

// ReportEdtIo is the golang structure for table report_edt_io.
type ReportEdtIo internal.ReportEdtIo

// Fill with you ideas below.

// ReportEdtIoApiReq 请求参数，用于前后端交互参数格式约定
type ReportEdtIoApiReq struct {
	ResID   string `v:"length:0,255 #可为空|长度应当在:min到:max之间"`
	BegDate string `v:"length:8,8 #长度应当在:min到:max之间"`
	EndDate string `v:"length:8,8 #长度应当在:min到:max之间"`
	SumKind string `v:"length:0,3 #长度应当在:min到:max之间"`
	Page    int
}

// ToSQL
func (r *ReportEdtIoApiReq) ToSQL() string {
	return fmt.Sprintf("'%s','%s','%s','%s'", r.ResID, r.BegDate, r.EndDate, r.SumKind)

}
