// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// Res is the golang structure for table res.
type Res internal.Res

// Fill with you ideas below.