// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// ResKind is the golang structure for table res_kind.
type ResKind internal.ResKind

// Fill with you ideas below.