// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// ResBom is the golang structure for table res_bom.
type ResBom internal.ResBom

// Fill with you ideas below.