// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// Subject is the golang structure for table subject.
type Subject internal.Subject

// Fill with you ideas below.