// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// Sup is the golang structure for table sup.
type Sup internal.Sup

// Fill with you ideas below.