// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// UserEmp is the golang structure for table user_emp.
type UserEmp internal.UserEmp

// Fill with you ideas below.