// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// Vr is the golang structure for table vr.
type Vr internal.Vr

// Fill with you ideas below.