// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrAmo is the golang structure for table vr_amo.
type VrAmo internal.VrAmo

// Fill with you ideas below.