// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrAmoItem is the golang structure for table vr_amo_item.
type VrAmoItem internal.VrAmoItem

// Fill with you ideas below.