// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrAmoSubject is the golang structure for table vr_amo_subject.
type VrAmoSubject internal.VrAmoSubject

// Fill with you ideas below.