// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrItem is the golang structure for table vr_item.
type VrItem internal.VrItem

// Fill with you ideas below.