// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrItemIo is the golang structure for table vr_item_io.
type VrItemIo internal.VrItemIo

// Fill with you ideas below.