// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrMainItem is the golang structure for table vr_main_item.
type VrMainItem internal.VrMainItem

// Fill with you ideas below.