// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrMain is the golang structure for table vr_main.
type VrMain internal.VrMain

// Fill with you ideas below.