// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrNum is the golang structure for table vr_num.
type VrNum internal.VrNum

// Fill with you ideas below.