// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrSubjectItem is the golang structure for table vr_subject_item.
type VrSubjectItem internal.VrSubjectItem

// Fill with you ideas below.