// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrSubject is the golang structure for table vr_subject.
type VrSubject internal.VrSubject

// Fill with you ideas below.