// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrSubjectInv is the golang structure for table vr_subject_inv.
type VrSubjectInv internal.VrSubjectInv

// Fill with you ideas below.