// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfast/app/model/internal"
)

// VrType is the golang structure for table vr_type.
type VrType internal.VrType

// Fill with you ideas below.