// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package vr_ba_item

import (
	"database/sql"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
	"time"
)

// arModel is a active record design model for table vr_ba_item operations.
type arModel struct {
	gmvc.M
}

var (
	// Table is the table name of vr_ba_item.
	Table = "vr_ba_item"
	// Model is the model object of vr_ba_item.
	Model = &arModel{g.DB("erp").Table(Table).Safe()}
	// Columns defines and stores column names for table vr_ba_item.
	Columns = struct {
		AssNum            string //   
        BatchNo           string //   
        CostPrice         string //   
        Discount          string //   
        DiscountAmount    string //   
        DiscountPrice     string //   
        InpAmount         string //   
        InpNum            string //   
        InpNumFactor      string //   
        InpPrice          string //   
        InpUnitTypeId     string //   
        IsMain            string //   
        ItemDateLmt       string //   
        ItemEdtId         string //   
        ItemEdtSiteId     string //   
        ItemFee1          string //   
        ItemFee2          string //   
        ItemId            string //   
        ItemTargetEdtId   string //   
        MainId            string //   
        NoteInfo          string //   
        ProduceDate       string //   
        RefItemId         string //   
        RefVoucherId      string //   
        RefVoucherNo      string //   
        RefVoucherType    string //   
        ResCostOpt        string //   
        ResId             string //   
        State             string //   
        StdNum            string //   
        StdUnitTypeId     string //   
        SubAttrVal1       string //   
        SubAttrVal2       string //   
        SubAttrVal3       string //   
        TagAmount         string //   
        TagPrice          string //   
        TaxAmount         string //   
        TaxPrice          string //   
        TaxRate           string //   
        TotalAmount       string //   
        VoucherId         string //   
        VrItemExt1        string //   
        VrItemExt2        string //   
        VrItemExt3        string //   
        VrItemExt4        string //   
        VrItemExt5        string //   
        VrItemExt6        string //   
        ItemEmfCenterId   string //   
        ItemEmfProcessId  string //
	}{
		AssNum:           "ass_num",              
        BatchNo:          "batch_no",             
        CostPrice:        "cost_price",           
        Discount:         "discount",             
        DiscountAmount:   "discount_amount",      
        DiscountPrice:    "discount_price",       
        InpAmount:        "inp_amount",           
        InpNum:           "inp_num",              
        InpNumFactor:     "inp_num_factor",       
        InpPrice:         "inp_price",            
        InpUnitTypeId:    "inp_unit_type_id",     
        IsMain:           "is_main",              
        ItemDateLmt:      "item_date_lmt",        
        ItemEdtId:        "item_edt_id",          
        ItemEdtSiteId:    "item_edt_site_id",     
        ItemFee1:         "item_fee_1",           
        ItemFee2:         "item_fee_2",           
        ItemId:           "item_id",              
        ItemTargetEdtId:  "item_target_edt_id",   
        MainId:           "main_id",              
        NoteInfo:         "note_info",            
        ProduceDate:      "produce_date",         
        RefItemId:        "ref_item_id",          
        RefVoucherId:     "ref_voucher_id",       
        RefVoucherNo:     "ref_voucher_no",       
        RefVoucherType:   "ref_voucher_type",     
        ResCostOpt:       "res_cost_opt",         
        ResId:            "res_id",               
        State:            "state",                
        StdNum:           "std_num",              
        StdUnitTypeId:    "std_unit_type_id",     
        SubAttrVal1:      "sub_attr_val_1",       
        SubAttrVal2:      "sub_attr_val_2",       
        SubAttrVal3:      "sub_attr_val_3",       
        TagAmount:        "tag_amount",           
        TagPrice:         "tag_price",            
        TaxAmount:        "tax_amount",           
        TaxPrice:         "tax_price",            
        TaxRate:          "tax_rate",             
        TotalAmount:      "total_amount",         
        VoucherId:        "voucher_id",           
        VrItemExt1:       "vr_item_ext_1",        
        VrItemExt2:       "vr_item_ext_2",        
        VrItemExt3:       "vr_item_ext_3",        
        VrItemExt4:       "vr_item_ext_4",        
        VrItemExt5:       "vr_item_ext_5",        
        VrItemExt6:       "vr_item_ext_6",        
        ItemEmfCenterId:  "item_emf_center_id",   
        ItemEmfProcessId: "item_emf_process_id",
	}
)

// As sets an alias name for current table.
func (m *arModel) As(as string) *arModel {
	return &arModel{m.M.As(as)}
}

// TX sets the transaction for current operation.
func (m *arModel) TX(tx *gdb.TX) *arModel {
	return &arModel{m.M.TX(tx)}
}

// Master marks the following operation on master node.
func (m *arModel) Master() *arModel {
	return &arModel{m.M.Master()}
}

// Slave marks the following operation on slave node.
// Note that it makes sense only if there's any slave node configured.
func (m *arModel) Slave() *arModel {
	return &arModel{m.M.Slave()}
}

// LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
func (m *arModel) LeftJoin(table ...string) *arModel {
	return &arModel{m.M.LeftJoin(table ...)}
}

// RightJoin does "RIGHT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").RightJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").RightJoin("user_detail", "ud", "ud.uid=u.uid")
func (m *arModel) RightJoin(table ...string) *arModel {
	return &arModel{m.M.RightJoin(table ...)}
}

// InnerJoin does "INNER JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").InnerJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").InnerJoin("user_detail", "ud", "ud.uid=u.uid")
func (m *arModel) InnerJoin(table ...string) *arModel {
	return &arModel{m.M.InnerJoin(table ...)}
}


// Option sets the extra operation option for the model.
func (m *arModel) Option(option int) *arModel {
	return &arModel{m.M.Option(option)}
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (m *arModel) OmitEmpty() *arModel {
	return &arModel{m.M.OmitEmpty()}
}

// Filter marks filtering the fields which does not exist in the fields of the operated table.
func (m *arModel) Filter() *arModel {
	return &arModel{m.M.Filter()}
}

// Where sets the condition statement for the model. The parameter <where> can be type of
// string/map/gmap/slice/struct/*struct, etc. Note that, if it's called more than one times,
// multiple conditions will be joined into where statement using "AND".
// Eg:
// Where("uid=10000")
// Where("uid", 10000)
// Where("money>? AND name like ?", 99999, "vip_%")
// Where("uid", 1).Where("name", "john")
// Where("status IN (?)", g.Slice{1,2,3})
// Where("age IN(?,?)", 18, 50)
// Where(User{ Id : 1, UserName : "john"})
func (m *arModel) Where(where interface{}, args ...interface{}) *arModel {
	return &arModel{m.M.Where(where, args...)}
}

// WherePri does the same logic as Model.Where except that if the parameter <where>
// is a single condition like int/string/float/slice, it treats the condition as the primary
// key value. That is, if primary key is "id" and given <where> parameter as "123", the
// WherePri function treats the condition as "id=123", but Model.Where treats the condition
// as string "123".
func (m *arModel) WherePri(where interface{}, args ...interface{}) *arModel {
	return &arModel{m.M.WherePri(where, args...)}
}

// And adds "AND" condition to the where statement.
func (m *arModel) And(where interface{}, args ...interface{}) *arModel {
	return &arModel{m.M.And(where, args...)}
}

// Or adds "OR" condition to the where statement.
func (m *arModel) Or(where interface{}, args ...interface{}) *arModel {
	return &arModel{m.M.Or(where, args...)}
}

// Group sets the "GROUP BY" statement for the model.
func (m *arModel) Group(groupBy string) *arModel {
	return &arModel{m.M.Group(groupBy)}
}

// Order sets the "ORDER BY" statement for the model.
func (m *arModel) Order(orderBy ...string) *arModel {
	return &arModel{m.M.Order(orderBy...)}
}

// Limit sets the "LIMIT" statement for the model.
// The parameter <limit> can be either one or two number, if passed two number is passed,
// it then sets "LIMIT limit[0],limit[1]" statement for the model, or else it sets "LIMIT limit[0]"
// statement.
func (m *arModel) Limit(limit ...int) *arModel {
	return &arModel{m.M.Limit(limit...)}
}

// Offset sets the "OFFSET" statement for the model.
// It only makes sense for some databases like SQLServer, PostgreSQL, etc.
func (m *arModel) Offset(offset int) *arModel {
	return &arModel{m.M.Offset(offset)}
}

// Page sets the paging number for the model.
// The parameter <page> is started from 1 for paging.
// Note that, it differs that the Limit function start from 0 for "LIMIT" statement.
func (m *arModel) Page(page, limit int) *arModel {
	return &arModel{m.M.Page(page, limit)}
}

// Batch sets the batch operation number for the model.
func (m *arModel) Batch(batch int) *arModel {
	return &arModel{m.M.Batch(batch)}
}

// Cache sets the cache feature for the model. It caches the result of the sql, which means
// if there's another same sql request, it just reads and returns the result from cache, it
// but not committed and executed into the database.
//
// If the parameter <duration> < 0, which means it clear the cache with given <name>.
// If the parameter <duration> = 0, which means it never expires.
// If the parameter <duration> > 0, which means it expires after <duration>.
//
// The optional parameter <name> is used to bind a name to the cache, which means you can later
// control the cache like changing the <duration> or clearing the cache with specified <name>.
//
// Note that, the cache feature is disabled if the model is operating on a transaction.
func (m *arModel) Cache(duration time.Duration, name ...string) *arModel {
	return &arModel{m.M.Cache(duration, name...)}
}

// Data sets the operation data for the model.
// The parameter <data> can be type of string/map/gmap/slice/struct/*struct, etc.
// Eg:
// Data("uid=10000")
// Data("uid", 10000)
// Data(g.Map{"uid": 10000, "name":"john"})
// Data(g.Slice{g.Map{"uid": 10000, "name":"john"}, g.Map{"uid": 20000, "name":"smith"})
func (m *arModel) Data(data ...interface{}) *arModel {
	return &arModel{m.M.Data(data...)}
}

// All does "SELECT FROM ..." statement for the model.
// It retrieves the records from table and returns the result as []*Entity.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
func (m *arModel) All(where ...interface{}) ([]*Entity, error) {
	all, err := m.M.All(where...)
	if err != nil {
		return nil, err
	}
	var entities []*Entity
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// One retrieves one record from table and returns the result as *Entity.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
func (m *arModel) One(where ...interface{}) (*Entity, error) {
	one, err := m.M.One(where...)
	if err != nil {
		return nil, err
	}
	var entity *Entity
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindOne retrieves and returns a single Record by Model.WherePri and Model.One.
// Also see Model.WherePri and Model.One.
func (m *arModel) FindOne(where ...interface{}) (*Entity, error) {
	one, err := m.M.FindOne(where...)
	if err != nil {
		return nil, err
	}
	var entity *Entity
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindAll retrieves and returns Result by by Model.WherePri and Model.All.
// Also see Model.WherePri and Model.All.
func (m *arModel) FindAll(where ...interface{}) ([]*Entity, error) {
	all, err := m.M.FindAll(where...)
	if err != nil {
		return nil, err
	}
	var entities []*Entity
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// Chunk iterates the table with given size and callback function.
func (m *arModel) Chunk(limit int, callback func(entities []*Entity, err error) bool) {
	m.M.Chunk(limit, func(result gdb.Result, err error) bool {
		var entities []*Entity
		err = result.Structs(&entities)
		if err == sql.ErrNoRows {
			return false
		}
		return callback(entities, err)
	})
}

// LockUpdate sets the lock for update for current operation.
func (m *arModel) LockUpdate() *arModel {
	return &arModel{m.M.LockUpdate()}
}

// LockShared sets the lock in share mode for current operation.
func (m *arModel) LockShared() *arModel {
	return &arModel{m.M.LockShared()}
}

// Unscoped enables/disables the soft deleting feature.
func (m *arModel) Unscoped() *arModel {
	return &arModel{m.M.Unscoped()}
}