// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// AppDefList is the golang structure for table app_def_list.
type AppDefList struct {
    Name   string `orm:"name,primary" json:"name"`   //   
    Select string `orm:"select"       json:"select"` //   
    From   string `orm:"from"         json:"from"`   //   
    Like   string `orm:"like"         json:"like"`   //   
    Del    string `orm:"del"          json:"del"`    //   
}