// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Check is the golang structure for table check.
type Check struct {
    VrId      int     `orm:"vr_id,primary" json:"vr_id"`       //   
    No        string  `orm:"no,unique"     json:"no"`          //   
    Amo       float64 `orm:"amo"           json:"amo"`         //   
    TypeId    string  `orm:"type_id"       json:"type_id"`     //   
    DueDate   string  `orm:"due_date"      json:"due_date"`    //   
    Payer     string  `orm:"payer"         json:"payer"`       //   
    Guarantee string  `orm:"guarantee"     json:"guarantee"`   //   
    EbaId     string  `orm:"eba_id"        json:"eba_id"`      //   
    EdtNum    int     `orm:"edt_num"       json:"edt_num"`     //   
    EdtTypeId string  `orm:"edt_type_id"   json:"edt_type_id"` //   
}