// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Edt is the golang structure for table edt.
type Edt struct {
    Id   int    `orm:"id,primary" json:"id"`   //   
    Name string `orm:"name"       json:"name"` //   
}