// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// EdtIo is the golang structure for table edt_io.
type EdtIo struct {
    VrDate         string  `orm:"vr_date"          json:"vr_date"`          //   
    VrId           int     `orm:"vr_id,primary"    json:"vr_id"`            //   
    ItId           int     `orm:"it_id,primary"    json:"it_id"`            //   
    BNum           float64 `orm:"b_num"            json:"b_num"`            //   
    INum           float64 `orm:"i_num"            json:"i_num"`            //   
    ONum           float64 `orm:"o_num"            json:"o_num"`            //   
    ENum           float64 `orm:"e_num"            json:"e_num"`            //   
    LastCost       float64 `orm:"last_cost"        json:"last_cost"`        //   
    Cost           float64 `orm:"cost"             json:"cost"`             //   
    IoPrice        float64 `orm:"io_price"         json:"io_price"`         //   
    BAmo           float64 `orm:"b_amo"            json:"b_amo"`            //   
    IAmo           float64 `orm:"i_amo"            json:"i_amo"`            //   
    OAmo           float64 `orm:"o_amo"            json:"o_amo"`            //   
    EAmo           float64 `orm:"e_amo"            json:"e_amo"`            //   
    EProfit        float64 `orm:"e_profit"         json:"e_profit"`         //   
    IProfit        float64 `orm:"i_profit"         json:"i_profit"`         //   
    SaleAmo        float64 `orm:"sale_amo"         json:"sale_amo"`         //   
    SaleProfit     float64 `orm:"sale_profit"      json:"sale_profit"`      //   
    SaleProfitRate float64 `orm:"sale_profit_rate" json:"sale_profit_rate"` //   
    ResId          string  `orm:"res_id"           json:"res_id"`           //   
    IoType         string  `orm:"io_type"          json:"io_type"`          //   
}