// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Emp is the golang structure for table emp.
type Emp struct {
    Id     string `orm:"id,primary"  json:"id"`     //   
    Name   string `orm:"name,unique" json:"name"`   //   
    Py     string `orm:"py"          json:"py"`     //   
    Mobile string `orm:"mobile"      json:"mobile"` //   
    Tel    string `orm:"tel"         json:"tel"`    //   
    Qq     string `orm:"qq"          json:"qq"`     //   
    Mail   string `orm:"mail"        json:"mail"`   //   
    State  string `orm:"state"       json:"state"`  //   
}