// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// InitEba is the golang structure for table init_eba.
type InitEba struct {
    EbaId string  `orm:"eba_id,primary" json:"eba_id"` //   
    QtNum float64 `orm:"qt_num"         json:"qt_num"` //   
}