// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// InitInvRes is the golang structure for table init_inv_res.
type InitInvRes struct {
    InvResId string  `orm:"inv_res_id,primary" json:"inv_res_id"` //   
    Num      float64 `orm:"num"                json:"num"`        //   
}