// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// InvEba is the golang structure for table inv_eba.
type InvEba struct {
    EbaId   string `orm:"eba_id,primary" json:"eba_id"`  //   
    TaxNo   string `orm:"tax_no,primary" json:"tax_no"`  //   
    Name    string `orm:"name"           json:"name"`    //   
    Py      string `orm:"py"             json:"py"`      //   
    Bank    string `orm:"bank"           json:"bank"`    //   
    Address string `orm:"address"        json:"address"` //   
    State   string `orm:"state"          json:"state"`   //   
    Note    string `orm:"note"           json:"note"`    //   
}