// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Res is the golang structure for table res.
type Res struct {
    Id           string  `orm:"id,primary"     json:"id"`             //   
    Name         string  `orm:"name,unique"    json:"name"`           //   
    Py           string  `orm:"py"             json:"py"`             //   
    Pack         float64 `orm:"pack"           json:"pack"`           //   
    Model        string  `orm:"model"          json:"model"`          //   
    FloorNum     float64 `orm:"floor_num"      json:"floor_num"`      //   
    Note         string  `orm:"note"           json:"note"`           //   
    ResKindId    int     `orm:"res_kind_id"    json:"res_kind_id"`    //   
    InvResIds    string  `orm:"inv_res_ids"    json:"inv_res_ids"`    //   
    InitNum      float64 `orm:"init_num"       json:"init_num"`       //   
    InitPrice    float64 `orm:"init_price"     json:"init_price"`     //   
    InitAmo      float64 `orm:"init_amo"       json:"init_amo"`       //   
    CreateDate   string  `orm:"create_date"    json:"create_date"`    //   
    CreateUserId int     `orm:"create_user_id" json:"create_user_id"` //   
    CheckDate    string  `orm:"check_date"     json:"check_date"`     //   
    CheckUserId  int     `orm:"check_user_id"  json:"check_user_id"`  //   
    State        string  `orm:"state"          json:"state"`          //   
}