// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// ResBom is the golang structure for table res_bom.
type ResBom struct {
    ResId    string  `orm:"res_id,primary"     json:"res_id"`     //   
    SubResId string  `orm:"sub_res_id,primary" json:"sub_res_id"` //   
    PerNum   float64 `orm:"per_num"            json:"per_num"`    //   
}