// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// ResKind is the golang structure for table res_kind.
type ResKind struct {
    Id   int    `orm:"id,primary"  json:"id"`   //   
    Name string `orm:"name,unique" json:"name"` //   
}