// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Subject is the golang structure for table subject.
type Subject struct {
    Id     string `orm:"id,primary" json:"id"`      //   
    Kind   string `orm:"kind"       json:"kind"`    //   
    Name   string `orm:"name"       json:"name"`    //   
    IoFlag string `orm:"io_flag"    json:"io_flag"` //   
    Py     string `orm:"py"         json:"py"`      //   
}