// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Sup is the golang structure for table sup.
type Sup struct {
    Id             string `orm:"id,primary"       json:"id"`               //   
    Name           string `orm:"name,unique"      json:"name"`             //   
    Py             string `orm:"py"               json:"py"`               //   
    Linkman        string `orm:"linkman"          json:"linkman"`          //   
    Tel            string `orm:"tel"              json:"tel"`              //   
    Fax            string `orm:"fax"              json:"fax"`              //   
    Mail           string `orm:"mail"             json:"mail"`             //   
    Address        string `orm:"address"          json:"address"`          //   
    OweAmountLimit int    `orm:"owe_amount_limit" json:"owe_amount_limit"` //   
    OweTimeLimit   int    `orm:"owe_time_limit"   json:"owe_time_limit"`   //   
    Bank           string `orm:"bank"             json:"bank"`             //   
    BankAccount    string `orm:"bank_account"     json:"bank_account"`     //   
    BankName       string `orm:"bank_name"        json:"bank_name"`        //   
    Note           string `orm:"note"             json:"note"`             //   
    EmpId          string `orm:"emp_id"           json:"emp_id"`           //   
    CreateDate     string `orm:"create_date"      json:"create_date"`      //   
    CreateUserId   int    `orm:"create_user_id"   json:"create_user_id"`   //   
    CheckDate      string `orm:"check_date"       json:"check_date"`       //   
    CheckUserId    int    `orm:"check_user_id"    json:"check_user_id"`    //   
    State          string `orm:"state"            json:"state"`            //   
}