// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// UserEmp is the golang structure for table user_emp.
type UserEmp struct {
    UserId   int    `orm:"user_id,primary"   json:"user_id"`    //   
    OitEmpId string `orm:"oit_emp_id,unique" json:"oit_emp_id"` //   
    UserName string `orm:"user_name,unique"  json:"user_name"`  //   
}