// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Vr is the golang structure for table vr.
type Vr struct {
    VrId         int    `orm:"vr_id,primary"  json:"vr_id"`          //   
    VrNo         string `orm:"vr_no,unique"   json:"vr_no"`          //   
    VrDate       string `orm:"vr_date"        json:"vr_date"`        //   
    VrType       string `orm:"vr_type"        json:"vr_type"`        //   
    VrNote       string `orm:"vr_note"        json:"vr_note"`        //   
    State        string `orm:"state"          json:"state"`          //   
    CreateDate   string `orm:"create_date"    json:"create_date"`    //   
    CreateUserId string `orm:"create_user_id" json:"create_user_id"` //   
    CheckDate    string `orm:"check_date"     json:"check_date"`     //   
    CheckUserId  string `orm:"check_user_id"  json:"check_user_id"`  //   
}