// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Vr is the golang structure for table vr.
type Vr struct {
    Vid          uint   `orm:"vid,primary"    json:"vid"`          //   
    Vno          string `orm:"vno,unique"     json:"vno"`          //   
    VrDate       string `orm:"vr_date"        json:"vrDate"`       //   
    VrNote       string `orm:"vr_note"        json:"vrNote"`       //   
    CreateDate   string `orm:"create_date"    json:"createDate"`   //   
    CheckDate    string `orm:"check_date"     json:"checkDate"`    //   
    CreateUserId uint   `orm:"create_user_id" json:"createUserId"` //   
    CheckUserId  uint   `orm:"check_user_id"  json:"checkUserId"`  //   
    VtypeId      uint   `orm:"vtype_id"       json:"vtypeId"`      //   
    StateId      uint   `orm:"state_id"       json:"stateId"`      //   
}