// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// VrAmo is the golang structure for table vr_amo.
type VrAmo struct {
    VrId         int     `orm:"vr_id,primary"   json:"vr_id"`          //   
    BillId       int     `orm:"bill_id,primary" json:"bill_id"`        //   
    BillNo       string  `orm:"bill_no"         json:"bill_no"`        //   
    BillDate     string  `orm:"bill_date"       json:"bill_date"`      //   
    BillMonth    string  `orm:"bill_month"      json:"bill_month"`     //   
    BillDateLmt  string  `orm:"bill_date_lmt"   json:"bill_date_lmt"`  //   
    BillNote     string  `orm:"bill_note"       json:"bill_note"`      //   
    Amo          float64 `orm:"amo"             json:"amo"`            //   
    PjId         string  `orm:"pj_id"           json:"pj_id"`          //   
    EmpId        string  `orm:"emp_id"          json:"emp_id"`         //   
    UnitId       string  `orm:"unit_id"         json:"unit_id"`        //   
    TaxNo        string  `orm:"tax_no"          json:"tax_no"`         //   
    Brand        string  `orm:"brand"           json:"brand"`          //   
    OrderDate    string  `orm:"order_date"      json:"order_date"`     //   
    TranDateLmt  string  `orm:"tran_date_lmt"   json:"tran_date_lmt"`  //   
    TranPrice    float64 `orm:"tran_price"      json:"tran_price"`     //   
    PrintPackNum float64 `orm:"print_pack_num"  json:"print_pack_num"` //   
    PrintAmo     float64 `orm:"print_amo"       json:"print_amo"`      //   
    KpiNum       float64 `orm:"kpi_num"         json:"kpi_num"`        //   
    KpiAmo       float64 `orm:"kpi_amo"         json:"kpi_amo"`        //   
    ISubject     string  `orm:"i_subject"       json:"i_subject"`      //   
    OSubject     string  `orm:"o_subject"       json:"o_subject"`      //   
    ISubjectInv  string  `orm:"i_subject_inv"   json:"i_subject_inv"`  //   
    OSubjectInv  string  `orm:"o_subject_inv"   json:"o_subject_inv"`  //   
}