// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// VrAmoItem is the golang structure for table vr_amo_item.
type VrAmoItem struct {
    VrId        int     `orm:"vr_id,primary" json:"vr_id"`         //   
    ItId        int     `orm:"it_id,primary" json:"it_id"`         //   
    Amo         float64 `orm:"amo"           json:"amo"`           //   
    ItNote      string  `orm:"it_note"       json:"it_note"`       //   
    RefBillId   int     `orm:"ref_bill_id"   json:"ref_bill_id"`   //   
    RefBillType string  `orm:"ref_bill_type" json:"ref_bill_type"` //   
    OitSubject  string  `orm:"oit_subject"   json:"oit_subject"`   //   
    OrgVrNo     string  `orm:"org_vr_no"     json:"org_vr_no"`     //   
    OrgVrDate   string  `orm:"org_vr_date"   json:"org_vr_date"`   //   
    OrgAmo      float64 `orm:"org_amo"       json:"org_amo"`       //   
}