// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// VrAmoSubject is the golang structure for table vr_amo_subject.
type VrAmoSubject struct {
    VrType       string `orm:"vr_type,primary" json:"vr_type"`        //                              
    AmoId        string `orm:"amo_id,primary"  json:"amo_id"`         // 1:vr_amo,2:main_item,3:item  
    ISubject     string `orm:"i_subject"       json:"i_subject"`      //                              
    IDescribe    string `orm:"i_describe"      json:"i_describe"`     //                              
    OSubject     string `orm:"o_subject"       json:"o_subject"`      //                              
    ODescribe    string `orm:"o_describe"      json:"o_describe"`     //                              
    ISubjectInv  string `orm:"i_subject_inv"   json:"i_subject_inv"`  //                              
    IDescribeInv string `orm:"i_describe_inv"  json:"i_describe_inv"` //                              
    OSubjectInv  string `orm:"o_subject_inv"   json:"o_subject_inv"`  //                              
    ODescribeInv string `orm:"o_describe_inv"  json:"o_describe_inv"` //                              
    IsBill       int    `orm:"is_bill"         json:"is_bill"`        //                              
    BillId       int    `orm:"bill_id"         json:"bill_id"`        //                              
    VrDescribe   string `orm:"vr_describe"     json:"vr_describe"`    //                              
}