// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// VrItem is the golang structure for table vr_item.
type VrItem struct {
    VrId      int     `orm:"vr_id,primary" json:"vr_id"`       //   
    ItId      int     `orm:"it_id,primary" json:"it_id"`       //   
    MainId    int     `orm:"main_id"       json:"main_id"`     //   
    Num       float64 `orm:"num"           json:"num"`         //   
    Price     float64 `orm:"price"         json:"price"`       //   
    Amo       float64 `orm:"amo"           json:"amo"`         //   
    TaxRate   float64 `orm:"tax_rate"      json:"tax_rate"`    //   
    TaxAmo    float64 `orm:"tax_amo"       json:"tax_amo"`     //   
    CostPrice float64 `orm:"cost_price"    json:"cost_price"`  //   
    CostAmo   float64 `orm:"cost_amo"      json:"cost_amo"`    //   
    ResId     string  `orm:"res_id"        json:"res_id"`      //   
    InvResId  string  `orm:"inv_res_id"    json:"inv_res_id"`  //   
    UnitId    string  `orm:"unit_id"       json:"unit_id"`     //   
    ItNote    string  `orm:"it_note"       json:"it_note"`     //   
    RefVrId   int     `orm:"ref_vr_id"     json:"ref_vr_id"`   //   
    RefItId   int     `orm:"ref_it_id"     json:"ref_it_id"`   //   
    RefVrNo   string  `orm:"ref_vr_no"     json:"ref_vr_no"`   //   
    RefVrType string  `orm:"ref_vr_type"   json:"ref_vr_type"` //   
    EdtIo     string  `orm:"edt_io"        json:"edt_io"`      //   
    InvIo     string  `orm:"inv_io"        json:"inv_io"`      //   
    QtIo      string  `orm:"qt_io"         json:"qt_io"`       //   
}