// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// VrItemIo is the golang structure for table vr_item_io.
type VrItemIo struct {
    VrType     string `orm:"vr_type,primary" json:"vr_type"`     //                              
    NumSign    int    `orm:"num_sign"        json:"num_sign"`    // 1:vr_amo,2:main_item,3:item  
    EdtIo      string `orm:"edt_io"          json:"edt_io"`      //                              
    InvIo      string `orm:"inv_io"          json:"inv_io"`      //                              
    QtIo       string `orm:"qt_io"           json:"qt_io"`       //                              
    VrDescribe string `orm:"vr_describe"     json:"vr_describe"` //                              
}