// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// VrMainItem is the golang structure for table vr_main_item.
type VrMainItem struct {
    VrId          int     `orm:"vr_id,primary"   json:"vr_id"`          //   
    MainId        int     `orm:"main_id,primary" json:"main_id"`        //   
    Num           float64 `orm:"num"             json:"num"`            //   
    Price         float64 `orm:"price"           json:"price"`          //   
    Amo           float64 `orm:"amo"             json:"amo"`            //   
    ResId         string  `orm:"res_id"          json:"res_id"`         //   
    InvResId      string  `orm:"inv_res_id"      json:"inv_res_id"`     //   
    PackNum       float64 `orm:"pack_num"        json:"pack_num"`       //   
    PackSpec      float64 `orm:"pack_spec"       json:"pack_spec"`      //   
    GuidePrice    float64 `orm:"guide_price"     json:"guide_price"`    //   
    DiscountPrice float64 `orm:"discount_price"  json:"discount_price"` //   
    PrintResName  string  `orm:"print_res_name"  json:"print_res_name"` //   
    PrintModel    string  `orm:"print_model"     json:"print_model"`    //   
    ItNote        string  `orm:"it_note"         json:"it_note"`        //   
    KpiNum        float64 `orm:"kpi_num"         json:"kpi_num"`        //   
    KpiAmo        float64 `orm:"kpi_amo"         json:"kpi_amo"`        //   
}