// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// VrSubject is the golang structure for table vr_subject.
type VrSubject struct {
    VrType      string `orm:"vr_type,primary" json:"vr_type"`      //                              
    IoFlag      int    `orm:"io_flag,primary" json:"io_flag"`      // 1:vr_amo,2:main_item,3:item  
    SubjectId   string `orm:"subject_id"      json:"subject_id"`   //                              
    SubjectName string `orm:"subject_name"    json:"subject_name"` //                              
    VrName      string `orm:"vr_name"         json:"vr_name"`      //                              
}