// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// VrSubjectItem is the golang structure for table vr_subject_item.
type VrSubjectItem struct {
    VrType     string `orm:"vr_type,primary" json:"vr_type"`      //                              
    Kind       string `orm:"kind,primary"    json:"kind"`         // 1:vr_amo,2:main_item,3:item  
    ISubjectId string `orm:"i_subject_id"    json:"i_subject_id"` //                              
    OSubjectId string `orm:"o_subject_id"    json:"o_subject_id"` //                              
    IDescribe  string `orm:"i_describe"      json:"i_describe"`   //                              
    ODescribe  string `orm:"o_describe"      json:"o_describe"`   //                              
    VrDescribe string `orm:"vr_describe"     json:"vr_describe"`  //                              
}