// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// VrType is the golang structure for table vr_type.
type VrType struct {
    VrType string `orm:"vr_type,primary" json:"vr_type"` //   
    VrName string `orm:"vr_name"         json:"vr_name"` //   
}