// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gfast/app/dao/internal"
)

// reportEdtIoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportEdtIoDao struct {
	*internal.ReportEdtIoDao
}

var (
	// ReportEdtIo is globally public accessible object for table report_edt_io operations.
	ReportEdtIo = &reportEdtIoDao{
		internal.ReportEdtIo,
	}
)

// Fill with you ideas below.