// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gfast/app/dao/internal"
)

// vrDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type vrDao struct {
	*internal.VrDao
}

var (
	// Vr is globally public accessible object for table vr operations.
	Vr = &vrDao{
		internal.Vr,
	}
)

// Fill with you ideas below.