// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gfast/app/dao/internal"
)

// vrAmoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type vrAmoDao struct {
	*internal.VrAmoDao
}

var (
	// VrAmo is globally public accessible object for table vr_amo operations.
	VrAmo = &vrAmoDao{
		internal.VrAmo,
	}
)

// Fill with you ideas below.