// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gfast/app/dao/internal"
)

// vrMainDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type vrMainDao struct {
	*internal.VrMainDao
}

var (
	// VrMain is globally public accessible object for table vr_main operations.
	VrMain = &vrMainDao{
		internal.VrMain,
	}
)

// Fill with you ideas below.