// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gfast/app/dao/internal"
)

// vrNumDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type vrNumDao struct {
	*internal.VrNumDao
}

var (
	// VrNum is globally public accessible object for table vr_num operations.
	VrNum = &vrNumDao{
		internal.VrNum,
	}
)

// Fill with you ideas below.