// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package res

// Entity is the golang structure for table res.
type Entity struct {
	AssUnitType          string  `orm:"ass_unit_type"          json:"ass_unit_type"`          //
	AutoCopyParentInfo   string  `orm:"auto_copy_parent_info"  json:"auto_copy_parent_info"`  //
	BarCode              string  `orm:"bar_code"               json:"bar_code"`               //
	BatchFlag            string  `orm:"batch_flag"             json:"batch_flag"`             //
	CeilNum              float64 `orm:"ceil_num"               json:"ceil_num"`               //
	CostCalMethod        string  `orm:"cost_cal_method"        json:"cost_cal_method"`        //
	CostPrice            float64 `orm:"cost_price"             json:"cost_price"`             //
	CreateDate           string  `orm:"create_date"            json:"create_date"`            //
	CreateUserId         string  `orm:"create_user_id"         json:"create_user_id"`         //
	DefaultEdtId         string  `orm:"default_edt_id"         json:"default_edt_id"`         //
	EasyCode             string  `orm:"easy_code"              json:"easy_code"`              //
	EdtCeilNum           float64 `orm:"edt_ceil_num"           json:"edt_ceil_num"`           //
	EdtFloorNum          float64 `orm:"edt_floor_num"          json:"edt_floor_num"`          //
	EdtIoFlag            string  `orm:"edt_io_flag"            json:"edt_io_flag"`            //
	EmfRouteId           string  `orm:"emf_route_id"           json:"emf_route_id"`           //
	Ext1                 string  `orm:"ext_1"                  json:"ext_1"`                  //
	Ext2                 string  `orm:"ext_2"                  json:"ext_2"`                  //
	Ext3                 string  `orm:"ext_3"                  json:"ext_3"`                  //
	Ext4                 string  `orm:"ext_4"                  json:"ext_4"`                  //
	Ext5                 string  `orm:"ext_5"                  json:"ext_5"`                  //
	Ext6                 string  `orm:"ext_6"                  json:"ext_6"`                  //
	Ext7                 string  `orm:"ext_7"                  json:"ext_7"`                  //
	Ext8                 string  `orm:"ext_8"                  json:"ext_8"`                  //
	FloorNum             float64 `orm:"floor_num"              json:"floor_num"`              //
	InCeilPrice          float64 `orm:"in_ceil_price"          json:"in_ceil_price"`          //
	InRefPrice           float64 `orm:"in_ref_price"           json:"in_ref_price"`           //
	LastModiDate         string  `orm:"last_modi_date"         json:"last_modi_date"`         //
	LastModiUserId       string  `orm:"last_modi_user_id"      json:"last_modi_user_id"`      //
	Manufacturer         string  `orm:"manufacturer"           json:"manufacturer"`           //
	NumDotNum            int     `orm:"num_dot_num"            json:"num_dot_num"`            //
	OrderId              int     `orm:"order_id"               json:"order_id"`               //
	OutFloorPrice        float64 `orm:"out_floor_price"        json:"out_floor_price"`        //
	OutRefPrice          float64 `orm:"out_ref_price"          json:"out_ref_price"`          //
	ParentResId          string  `orm:"parent_res_id"          json:"parent_res_id"`          //
	PriceDotNum          int     `orm:"price_dot_num"          json:"price_dot_num"`          //
	QualityDays          int     `orm:"quality_days"           json:"quality_days"`           //
	ResCatId             string  `orm:"res_cat_id"             json:"res_cat_id"`             //
	ResDesc              string  `orm:"res_desc"               json:"res_desc"`               //
	ResId                string  `orm:"res_id,unique"          json:"res_id"`                 //
	ResKind              string  `orm:"res_kind"               json:"res_kind"`               //
	ResModel             string  `orm:"res_model"              json:"res_model"`              //
	ResName              string  `orm:"res_name"               json:"res_name"`               //
	ResPlace             string  `orm:"res_place"              json:"res_place"`              //
	ResRank              string  `orm:"res_rank"               json:"res_rank"`               //
	ResSpec              string  `orm:"res_spec"               json:"res_spec"`               //
	ResUnitType          string  `orm:"res_unit_type"          json:"res_unit_type"`          //
	StopFlag             string  `orm:"stop_flag"              json:"stop_flag"`              //
	SubjectSellCost      string  `orm:"subject_sell_cost"      json:"subject_sell_cost"`      //
	SubjectSellIncome    string  `orm:"subject_sell_income"    json:"subject_sell_income"`    //
	SubjectStorageAmount string  `orm:"subject_storage_amount" json:"subject_storage_amount"` //
	SupId                string  `orm:"sup_id"                 json:"sup_id"`                 //
	Homepage             string  `orm:"homepage"               json:"homepage"`               //
}
