// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package res_kind

// Entity is the golang structure for table res_kind.
type Entity struct {
	BuyFlag       string `orm:"buy_flag"        json:"buy_flag"`        //
	Name          string `orm:"name"            json:"name"`            //
	ResKind       string `orm:"res_kind,unique" json:"res_kind"`        //
	ResSupplyMode string `orm:"res_supply_mode" json:"res_supply_mode"` //
	SellFlag      string `orm:"sell_flag"       json:"sell_flag"`       //
}
