// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package model

// VrAmo is the golang structure for table vr_amo.
type VrAmo struct {
	ID          uint    `orm:"id,primary"   json:"id"`           //
	VID         uint    `orm:"vid,primary"   json:"vid"`         //
	Amo         float64 `orm:"amo"           json:"amo"`         //
	ItNote      string  `orm:"it_note"       json:"itNote"`      //
	RefBillID   int     `orm:"ref_bill_id"   json:"refBillId"`   //
	RefBillType string  `orm:"ref_bill_type" json:"refBillType"` //
	OitSubject  string  `orm:"oit_subject"   json:"oitSubject"`  //
	OrgVrNo     string  `orm:"org_vr_no"     json:"orgVrNo"`     //
	OrgVrDate   string  `orm:"org_vr_date"   json:"orgVrDate"`   //
	OrgAmo      float64 `orm:"org_amo"       json:"orgAmo"`      //
}
