// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package model

// VrMain is the golang structure for table vr_main.
type VrMain struct {
	ID           uint    `orm:"id,primary"   json:"id"`              //
	VID          uint    `orm:"vid,primary"     json:"vid"`          //
	BillNo       string  `orm:"bill_no"         json:"billNo"`       //
	BillDate     string  `orm:"bill_date"       json:"billDate"`     //
	BillMonth    string  `orm:"bill_month"      json:"billMonth"`    //
	BillLmtDate  string  `orm:"bill_lmt_date"   json:"billLmtDate"`  //
	Note         string  `orm:"note"       json:"note"`              //
	Amo          float64 `orm:"amo"             json:"amo"`          //
	TranDate     string  `orm:"tran_date"       json:"tranDate"`     //
	TranPrice    float64 `orm:"tran_price"      json:"tranPrice"`    //
	PrintPackNum float64 `orm:"print_pack_num"  json:"printPackNum"` //
	PrintAmo     float64 `orm:"print_amo"       json:"printAmo"`     //
	KpiNum       float64 `orm:"kpi_num"         json:"kpiNum"`       //
	KpiAmo       float64 `orm:"kpi_amo"         json:"kpiAmo"`       //
	ISubjectInv  string  `orm:"i_subject_inv"   json:"iSubjectInv"`  //
	OSubjectInv  string  `orm:"o_subject_inv"   json:"oSubjectInv"`  //
	BrandID      uint    `orm:"brand_id"        json:"brandId"`      //
	EmpID        uint    `orm:"emp_id"          json:"empId"`        //
	PjID         uint    `orm:"pj_id"           json:"pjId"`         //
	InvebaID     uint    `orm:"inveba_id"       json:"invebaId"`     //
	ISubjectID   uint    `orm:"i_subject_id"    json:"iSubjectId"`   //
	OSubjectID   uint    `orm:"o_subject_id"    json:"oSubjectId"`   //
	EbaID        uint    `orm:"eba_id"          json:"ebaId"`        //
	SupID        uint    `orm:"sup_id"          json:"supId"`        //
}
