// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package model

// VrPf is the golang structure for table vr_num.
type VrPf struct {
	ID         uint    `orm:"id,primary"  json:"id"`
	VID        uint    `orm:"vid"  json:"vid"` //
	IID        uint    `orm:"iid"  json:"iid"`
	ResID      uint    `orm:"res_id"       json:"resId"`      //
	PerPackNum float64 `orm:"per_pack_num" json:"perPackNum"` //
	Num        float64 `orm:"num"          json:"num"`        //
	Price      float64 `orm:"price"        json:"price"`      //
	Amo        float64 `orm:"amo"          json:"amo"`        //
	ItNote     string  `orm:"it_note"      json:"itNote"`     //
}
