// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"

	"gfast/app/model"
)

// ReportEdtIoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ReportEdtIoDao struct {
	DB      gdb.DB
	Sql     string
	Columns reportEdtIoColumns
}

// ReportEdtIoColumns defines and stores column names for table report_edt_io.
type reportEdtIoColumns struct {
	VrDescribe     string //
	VrNo           string //
	Name           string //
	VrDate         string //
	VrId           string //
	ItId           string //
	BNum           string //
	INum           string //
	ONum           string //
	ENum           string //
	LastCost       string //
	Cost           string //
	IoPrice        string //
	BAmo           string //
	IAmo           string //
	OAmo           string //
	EAmo           string //
	EProfit        string //
	IProfit        string //
	SaleAmo        string //
	SaleProfit     string //
	SaleProfitRate string //
	ResId          string //
	IoType         string //
}

var (
	// ReportEdtIo is globally public accessible object for table report_edt_io operations.
	ReportEdtIo = &ReportEdtIoDao{
		DB:  g.DB("erp"),
		Sql: "call kyerp.rep_edt_io",
		Columns: reportEdtIoColumns{
			VrDescribe:     "单据名称",
			VrNo:           "单号",
			Name:           "品名",
			VrDate:         "日期",
			VrId:           "单据流水",
			ItId:           "条目流水",
			BNum:           "期初数",
			INum:           "入库数",
			ONum:           "出库数",
			ENum:           "期末数",
			LastCost:       "上次成本",
			Cost:           "本次成本",
			IoPrice:        "价格",
			BAmo:           "期初金额",
			IAmo:           "入库金额",
			OAmo:           "出库金额",
			EAmo:           "期末金额",
			EProfit:        "盘点盈亏",
			IProfit:        "行情盈亏",
			SaleAmo:        "销售金额",
			SaleProfit:     "销售毛利",
			SaleProfitRate: "销售毛利率",
			ResId:          "产品编号",
			IoType:         "成本类型",
		},
	}
)

// Get retrieves and returns Result by by M.WherePri and M.All.
// Also see M.WherePri and M.All.
func (d *ReportEdtIoDao) Get(where string) ([]*model.ReportEdtIo, error) {
	var entities []*model.ReportEdtIo
	sql := d.Sql + "(" + where + ")"
	err := d.DB.GetStructs(&entities, sql)
	if err != nil {
		return nil, err
	}
	return entities, nil
}
